version: "3"
services:
  rabbitmq:
    image: rabbitmq:3.10.7-management
    hostname: rabbitmq
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 5s
      timeout: 10s
      retries: 5
      start_period: 4s
    environment:
      - RABBITMQ_DEFAULT_USER=user
      - RABBITMQ_DEFAULT_PASS=password
    ports:
      - 15672:15672
      - 5672:5672

  mongodb:
    image: mongo:latest
    hostname: mongodb
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=mongoadmin
      - MONGO_INITDB_ROOT_PASSWORD=secret

  routes_app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      rabbitmq:
        condition: service_healthy
    ports:
      - "8000:8000"
    environment:
      - rabbitmq_url=amqp://user:password@rabbitmq:5672/
      - mongodb_url=mongodb://mongoadmin:secret@mongodb:27017/
    volumes:
      - ./routes.json:/app/routes.json
      - ./routes_app.log:/app/routes_app.log
      - ./routes_app_timing.log:/app/routes_app_timing.log
