name: CI

on: [push]

jobs:
  test:
    name: Unit tests and linter
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run mypy
      run: mypy src tests --explicit-package-bases --ignore-missing-imports

    - name: Run pytest
      run: python -m pytest tests/unit

  e2e:
    name: Run end-to-end tests
    runs-on: ubuntu-latest
    needs: [test]
    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Start containers
      id: start-containers
      run: |
        docker-compose -f "docker-compose.yml" up -d --build
        sleep 5
        docker-compose -f "docker-compose.yml" logs

    - name: Install Python and pytest
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: pip install -r requirements.txt
    - name: Before e2e
      run: python before_e2e.py
    - name: Run end-to-end tests
      run: python -m pytest tests/e2e
      if: steps.start-containers.outcome == 'success'
    - name: After e2e
      run: python after_e2e.py
    - name: Stop containers
      if: always()
      run: docker-compose -f "docker-compose.yml" down
  
  docker:
    name: Publishes to Docker Hub
    runs-on: ubuntu-latest
    needs: [e2e]
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: gaponukz/atass-routes:latest
      